class KeyboardKeys {
  static const Map<String, int> appKeyMap = {
    'Yok (Devre Dışı)': 0,
    'Tuş 1': 1,
    'Tuş 2': 2,
    'Tuş 3': 3,
    'Tuş 4': 4,
    'Tuş 5': 5,
    'Tuş 6': 6,
    'Tuş 7': 7,
    'Tuş 8': 8,
    'Tuş 9': 9,
    'Tuş 10': 10,
    'Tuş 11': 11,
    'Tuş 12': 12,
    'Tuş 13': 13,
    'Tuş 14': 14,
    'Tuş 15': 15,
    'Tuş 16': 16,
    'Fare: Sol Tık': 101,
    'Fare: Orta Tık': 102,
    'Fare: Sağ Tık': 103,
    'Klavye: Yukarı Ok': 38,
    'Klavye: Aşağı Ok': 40,
    'Klavye: Sol Ok': 37,
    'Klavye: Sağ Ok': 39,
    'Klavye: Backspace': 8,
    'Klavye: Tab': 9,
    'Klavye: Enter': 13,
    'Klavye: Shift': 16,
    'Klavye: Ctrl': 17,
    'Klavye: Alt': 18,
    'Klavye: Pause': 19,
    'Klavye: Caps Lock': 20,
    'Klavye: Esc': 27,
    'Klavye: Space': 32,
    'Klavye: Page Up': 33,
    'Klavye: Page Down': 34,
    'Klavye: End': 35,
    'Klavye: Home': 36,
    'Klavye: A': 65,
    'Klavye: B': 66,
    'Klavye: C': 67,
    'Klavye: D': 68,
    'Klavye: E': 69,
    'Klavye: F': 70,
    'Klavye: G': 71,
    'Klavye: H': 72,
    'Klavye: I': 73,
    'Klavye: J': 74,
    'Klavye: K': 75,
    'Klavye: L': 76,
    'Klavye: M': 77,
    'Klavye: N': 78,
    'Klavye: O': 79,
    'Klavye: P': 80,
    'Klavye: Q': 81,
    'Klavye: R': 82,
    'Klavye: S': 83,
    'Klavye: T': 84,
    'Klavye: U': 85,
    'Klavye: V': 86,
    'Klavye: W': 87,
    'Klavye: X': 88,
    'Klavye: Y': 89,
    'Klavye: Z': 90,
  };
}
